### ISSUE TITLE
Sign up with a Facebook account

### ISSUE THREAD

**Issue by Ronan525** [Ronan525/love-running#2]
### User Story

In order to **sign up** as a **user**, I can **sign up with my Facebook account**.

### Acceptance Criteria:

A **button** encouraging the user to **sign in via Facebook**.

A **new page** which **allows Facebook to automatically create an account**.

### Tasks

- [ ] Create a new page which prompts the user to sign into the Facebook account.

- [ ] Create a button next to the create account button which opens the page in a new tab.

- [ ] Upon sign in to Facebook, create a new account for the user synced to their Facebook.
